#!/usr/bin/env ruby
require 'tmpdir'
require 'timeout'
require 'fileutils'
BUILD_TIMEOUT_IN_SECONDS = 1200
def sh(cmd)
  ok = system(cmd)
  raise RuntimeError unless ok
  ok
end

Dir.mktmpdir do |tmpdir|
  FileUtils.copy("test.sh", tmpdir)
  Dir.chdir(tmpdir) do
    begin
      Timeout.timeout(BUILD_TIMEOUT_IN_SECONDS) do
        sh("bash -e -x -u ./test.sh")
      end
    rescue Timeout
      puts 'Build took too long, killing the VM'
    ensure
      sh('vagrant destroy --force')
    end
  end
end
